AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HighScoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30  # Increase timeout from default 3 seconds
      Environment:
        Variables:
          DYNAMODB_TABLE: high-scores-table
          LOCAL_TESTING: true
          AWS_ENDPOINT_URL: 'http://localstack:4566'
      Events:
        HighScores:
          Type: Api
          Properties:
            Path: /high-scores
            Method: get
